routes/web.php
<?php

use App\Http\Controllers\Backstage\CampaignsController;
use App\Http\Controllers\Backstage\DashboardController;
use App\Http\Controllers\Backstage\PrizeController;
use App\Http\Controllers\Backstage\SymbolsController;
use App\Http\Controllers\Backstage\GameController;
use App\Http\Controllers\Backstage\UserController;
use App\Http\Controllers\Backstage\WinnerLineController;
use App\Http\Controllers\FrontendController;
use Illuminate\Support\Facades\Route;


Route::prefix('backstage')->name('backstage.')->middleware(['auth', 'setActiveCampaign'])->group(function () {

    // Dashboard
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    // Campaigns
    Route::get('campaigns/{campaign}/use', [CampaignsController::class, 'use'])->name('campaigns.use');
    Route::resource('campaigns', CampaignsController::class);

    Route::group(['middleware' => ['redirectIfNoActiveCampaign']], function () {
        Route::resource('games', GameController::class);
        Route::resource('prizes', PrizeController::class);
    });

    // Users
    Route::resource('users', UserController::class);
    Route::resource('symbols', SymbolsController::class);
    Route::resource('winner-lines', WinnerLineController::class);
});

// Route::prefix('backstage')->middleware('setActiveCampaign')->group(function () {
//     // Account activation
//     Route::get('activate/{ott}', 'Auth\ActivateAccountController@index')->name('backstage.activate.show');
//     Route::put('activate/{ott}', 'Auth\ActivateAccountController@update')->name('backstage.activate.update');
// });

Route::get('{campaign:slug}', [FrontendController::class, 'loadCampaign']);
Route::get('/', [FrontendController::class, 'loadCampaign']);

app/Http/Controllers/Backstage/CampaignsController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backstage\Campaigns\UpdateRequest;
use App\Models\Campaign;
use Carbon\Carbon;

class CampaignsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('backstage.campaigns.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backstage.campaigns.create', [
            'campaign' => new Campaign(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        // Validation
        $data = $this->validate(request(), [
            'name' => 'required|unique:campaigns|max:255',
            'timezone' => 'required',
            'starts_at' => 'required|date_format:d-m-Y H:i:s',
            'ends_at' => 'required|date_format:d-m-Y H:i:s',
        ]);

        //parse dates from campaign's timezone
        $startDate = Carbon::createFromFormat('d-m-Y H:i:s', $data['starts_at'], $data['timezone'])
            ->setTimezone('UTC');
        $data['starts_at'] = $startDate;

        $startDate = Carbon::createFromFormat('d-m-Y H:i:s', $data['ends_at'], $data['timezone'])
            ->setTimezone('UTC');
        $data['ends_at'] = $startDate;

        // Create the campaign
        $campaign = Campaign::create($data);

        // Set message
        session()->flash('success', 'The campaign has been created!');

        // Redirect
        return redirect()->route('backstage.campaigns.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Campaign $campaign
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Campaign $campaign)
    {
        return view('backstage.campaigns.edit', compact('campaign'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param Campaign $campaign
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Campaign $campaign)
    {
        // Validation
        $data = $this->validate(request(), [
            'name' => 'required|max:255|unique:campaigns,name,'.$campaign->id,
            'timezone' => 'required',
            'starts_at' => 'required|date_format:d-m-Y H:i:s',
            'ends_at' => 'required|date_format:d-m-Y H:i:s',
        ]);

        //parse dates from campaign's timezone
        $startDate = Carbon::createFromFormat('d-m-Y H:i:s', $data['starts_at'], $data['timezone'])->setTimezone('UTC');
        $data['starts_at'] = $startDate;

        $startDate = Carbon::createFromFormat('d-m-Y H:i:s', $data['ends_at'], $data['timezone'])->setTimezone('UTC');
        $data['ends_at'] = $startDate;

        // Update the campaigns data
        $campaign->update($data);

        // Redirect
        session()->flash('success', 'The campaign details have been saved!');

        return redirect()->route('backstage.campaigns.edit', $campaign->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Campaign $campaign
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Campaign $campaign)
    {
        $campaign->forceDelete();

        if (request()->ajax()) {
            return response()->json(['status' => 'success']);
        }

        session()->flash('success', 'The campaign has been removed!');

        return redirect(route('backstage.campaigns.index'));
    }

    public function use(Campaign $campaign)
    {
        session()->put('activeCampaign', $campaign->id);

        return redirect()->route('backstage.campaigns.index');
    }
}

app/Http/Controllers/Backstage/DashboardController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backstage.dashboard.index');
    }
}

app/Http/Controllers/Backstage/GameController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backstage\Campaigns\UpdateRequest;
use App\Models\Campaign;
use Illuminate\Support\Facades\Storage;

class GameController extends Controller
{
    public function __construct()
    {
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('backstage.games.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backstage.games.create', [
            'campaign' => new Campaign(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Campaign $campaign
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit()
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param Campaign $campaign
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update()
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Campaign $campaign
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Campaign $campaign)
    {
        //
    }
}

app/Http/Controllers/Backstage/PrizeController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backstage\Prizes\UpdateRequest;
use App\Models\Prize;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\View;

class PrizeController extends Controller
{
    public function __construct()
    {
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backstage.prizes.index');
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $prize = new Prize();
        // Return the view
        return view('backstage.prizes.create', compact('prize'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store()
    {
        // Validation
        $data = $this->validate(request(), [
            'name' => 'required|max:255',
            'description' => 'sometimes',
            'weight' => 'required|numeric|between:0.01,99.99',
            'starts_at' => 'required|date_format:d-m-Y H:i:s',
            'ends_at' => 'required|date_format:d-m-Y H:i:s',
            'level' => 'required|in:low,med,high',
        ]);

        // Add the campaign id to the data array.
        $data['campaign_id'] = session('activeCampaign');

        // Create the prize
        $prize = Prize::create($data);

        // Redirect with success message
        session()->flash('success', 'The prize has been created!');

        return redirect('/backstage/prizes');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Prize $prize)
    {
        return view('backstage.prizes.show', [
            'prize' => $prize,

        ]);
    }

    /**
     * Show the form for editing the specified resource.
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Prize $prize)
    {
        // Return the view
        return view('backstage.prizes.edit', compact('prize'));
    }

    /**
     * Update the specified resource in storage.
     * @param UpdateRequest $request
     * @param Prize $prize
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, Prize $prize)
    {
        // Validation
        $data = $this->validate(request(), [
            'title' => 'required|max:255',
            'weight' => 'required|numeric|between:0.01,99.99',
            'startsAt' => 'required|date_format:Y-m-d H:i:s',
            'endsAt' => 'required|date_format:Y-m-d H:i:s',
            'description' => 'sometimes',
            'level' => 'required|in:low,med,high',
        ]);

        // Add the currentPeriod to the data array.
        $data['campaign_id'] = session('currentCampaign');

        // Create the prize
        $prize->update($data);

        // Redirect with success message
        session()->flash('success', 'The prize has been updated!');

        return redirect('/backstage/prizes/'.$prize->id.'/edit');
    }

    /**
     * Remove the specified resource from storage.
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(Prize $prize)
    {
        $prize->forceDelete();

        if (request()->ajax()) {
            return response()->json(['status' => 'success']);
        }

        session()->flash('success', 'The prize has been removed!');

        return redirect(route('backstage.prizes.index'));
    }
}

app/Http/Controllers/Backstage/SymbolsController.php
<?php

namespace App\Http\Controllers\Backstage;

use App\Http\Controllers\Controller;
use App\Models\Symbol;
use App\Http\Requests\Backstage\Symbol\{
    StoreRequest,
    UpdateRequest
};
use File;


class SymbolsController extends Controller
{

    /**
     * Symbol mode instance;
     */
    private $__symbol;
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('backstage.symbols.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('backstage.symbols.create', [
            'symbol' => new Symbol(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param App\Http\Requests\Backstage\Symbol\StoreRequest; $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        // Validation
        $symbol = new Symbol();
        $data = $request->only(['status', 'points']);
        
        if(!$symbol->canChangeStatus($request->status,$symbol->id)){
            if($request->status == Symbol::STATUS_ACTIVE){
                session()->flash('error', trans('validation.custom.symbol.max_actve_limit',['limit'=>Symbol::MAXIMUM_ACTIVE_SYMBOLS]));
            }else{
                session()->flash('error', trans('validation.custom.symbol.min_inactve_limit', ['limit'=>Symbol::MIMIMUM_ACTIVE_SYMBOLS]));
            }
            return redirect()->route('backstage.symbols.create')->withInput();
        }
        if ($request->hasFile('symbol')) {
            $filenameWithExt = $request->file('symbol')->getClientOriginalName ();
            // Get Filename
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            // Get just Extension
            $extension = $request->file('symbol')->getClientOriginalExtension();
            // Filename To store
            $fileNameToStore = $filename. '_'. time().'.'.$extension;
            $request->file('symbol')->move(public_path(Symbol::SYMBOL_FOLDER), $fileNameToStore);
            $data['symbol'] = $fileNameToStore;
        }
        // Create the Symbol
        Symbol::create($data);

        // Set message
        session()->flash('success', trans('messages.symbol.success.created'));
        // Redirect
        return redirect()->route('backstage.symbols.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Symbol $symbol
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Symbol $symbol)
    {
        return view('backstage.symbols.edit', compact('symbol'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param App\Http\Requests\Backstage\Symbol\UpdateRequest; $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, $id)
    {
        $symbol = Symbol::find($id);
        $data = $request->only(['status', 'points']);
        if(!$symbol->canChangeStatus($request->status,$id)){
            if($request->status == Symbol::STATUS_ACTIVE){
                session()->flash('error', trans('validation.custom.symbol.max_actve_limit',['limit'=>Symbol::MAXIMUM_ACTIVE_SYMBOLS]));
            }else{
                session()->flash('error', trans('validation.custom.symbol.min_inactve_limit', ['limit'=>Symbol::MIMIMUM_ACTIVE_SYMBOLS]));
            }
            return redirect()->route('backstage.symbols.create')->withInput();
        }
        
        if ($request->hasFile('symbol')) {
            $filenameWithExt = $request->file('symbol')->getClientOriginalName ();
            // Get Filename
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            // Get just Extension
            $extension = $request->file('symbol')->getClientOriginalExtension();
            // Filename To store
            $fileNameToStore = $filename. '_'. time().'.'.$extension;
            $p = $request->file('symbol')->move(public_path(Symbol::SYMBOL_FOLDER), $fileNameToStore);
            $data['symbol'] = $fileNameToStore;
        }
        // Update the symbol data
        $symbol->update($data);
        // Redirect
        session()->flash('success', trans('messages.symbol.success.updated'));

        return redirect()->route('backstage.symbols.edit', $symbol->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Symbol $symbol
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Symbol $symbol)
    {
        
        File::delete($symbol->symbol_path);
        $symbol->forceDelete();

        if (request()->ajax()) {
            return response()->json(['status' => 'success']);
        }
        session()->flash('success', trans('messages.symbol.success.deleted'));

        return redirect(route('backstage.symbols.index'));
    }

}

resources/views/backstage/partials/flash-messages.blade.php
<script>

    @if( Session::has('success') )
        swal({
            title: "Great!",
            text: "{{ Session::get('success') }}",
            timer: 1500,
            button: false,
            icon: 'success'
        });
    @endif
    @if( Session::has('error') )
        swal({
            title: "Oops!",
            text: "{{ Session::get('error') }}",
            timer: 3000,
            button: false,
            icon: 'error'
        });
    @endif

</script>

resources/views/backstage/partials/navigation.blade.php
<nav>

    <p class="nav-header">Navigation</p>

    <a href="{{ route('backstage.dashboard') }}" class="@if( request()->segment(2) === 'dashboard' || !request()->segment(2)) active @endif mb-2 group flex items-center text-sm leading-5 font-medium text-gray-900 hover:text-gray-900 hover:no-underline focus:outline-none transition ease-in-out duration-150">
        <span class="icon-holder"><i class="fa-solid fa-gauge navigation-icon"></i></span>
        <span class="text">Dashboard</span>
    </a>

    <a href="{{ route('backstage.campaigns.index') }}" class="@if( request()->segment(2) === 'campaigns' && (!isset($activeCampaign) || request()->segment(3) != $activeCampaign->id)) ) active @endif mb-2 group flex items-center text-sm leading-5 font-medium text-gray-900 hover:text-gray-900 hover:no-underline focus:outline-none transition ease-in-out duration-150">
        <span class="icon-holder"><i class="fa-solid fa-bullhorn navigation-icon"></i></span>
        <span class="text">Campaigns</span>
    </a>

    <a href="{{ route('backstage.games.index') }}" class="@if( request()->segment(2) === 'games' ) active @endif mb-2 group flex items-center text-sm leading-5 font-medium text-gray-900 hover:text-gray-900 hover:no-underline focus:outline-none transition ease-in-out duration-150">
        <span class="icon-holder"><i class="fa-solid fa-play-circle navigation-icon"></i></span>
        <span class="text">Games</span>
    </a>

    <a href="{{ route('backstage.symbols.index') }}" class="@if( request()->segment(2) === 'symbols' ) active @endif mb-2 group flex items-center text-sm leading-5 font-medium text-gray-900 hover:text-gray-900 hover:no-underline focus:outline-none transition ease-in-out duration-150">
        <span class="icon-holder"><i class="fa-solid fa-icons navigation-icon"></i></span>
        <span class="text">Symbols</span>
    </a>
    <a href="{{ route('backstage.winner-lines.index') }}" class="@if( request()->segment(2) === 'winner-lines' ) active @endif mb-2 group flex items-center text-sm leading-5 font-medium text-gray-900 hover:text-gray-900 hover:no-underline focus:outline-none transition ease-in-out duration-150">
        <span class="icon-holder"><i class="fa-solid fa-trophy navigation-icon"></i></span>
        <span class="text">Winner lines</span>
    </a>

    @if( $activeCampaign )
    
        <a href="{{ route('backstage.prizes.index') }}" class="@if( request()->segment(2) === 'prizes' ) active @endif mb-2 group flex items-center text-sm leading-5 font-medium text-gray-900 hover:text-gray-900 hover:no-underline focus:outline-none transition ease-in-out duration-150">
            <span class="icon-holder"><i class="fa-solid fa-trophy navigation-icon"></i></span>
            <span class="text">Prizes</span>
        </a>

        <a href="{{ route( auth()->user()->isAdmin() ? 'backstage.campaigns.edit' : 'backstage.campaigns.show', $activeCampaign->id) }}" class="@if( request()->segment(2) === 'campaigns' && request()->segment(3) == $activeCampaign->id) active @endif mb-2 group flex items-center text-sm leading-5 font-medium text-gray-900 hover:text-gray-900 hover:no-underline focus:outline-none transition ease-in-out duration-150">
            <span class="icon-holder"><i class="fa-solid fa-sliders navigation-icon"></i></span>
            <span class="text">Settings</span>
        </a>
    @endif

    @if( auth()->user()->isAdmin())
    <a href="{{ route('backstage.users.index') }}" class="@if( request()->segment(2) === 'users' ) active @endif mb-2 group flex items-center text-sm leading-5 font-medium text-gray-900 hover:text-gray-900 hover:no-underline focus:outline-none transition ease-in-out duration-150">
        <span class="icon-holder"><i class="fa-solid fa-users navigation-icon"></i></span>
        <span class="text">Users</span>
    </a>
    @endif
    
</nav>

resources/views/backstage/partials/support.blade.php
@if( app()->environment() === 'production' )
    <script>
        window.fwSettings={
            'widget_id':36000000116
        };
        !function(){if("function"!=typeof window.FreshworksWidget){var n=function(){n.q.push(arguments)};n.q=[],window.FreshworksWidget=n}}()
    </script>
    <script type='text/javascript' src='https://widget.freshworks.com/widgets/36000000116.js' async defer></script>
@endif